### ISSUE TITLE
不能自动开启下一局 for 手机

### ISSUE THREAD

**Issue by UnspokenSpell** [Xizo-114514/Phigros-Script#1]
## 问题描述
如果设备是手机，那么会卡在结算界面，无法自动化。如果是蓝叠，则正常。

## 复现步骤
0. 将**手机**和电脑用USB线缆连接
1. Phigros进入暂停
2. 开启脚本的自动打歌
3. 完成一次打歌，进入结算界面
4. 一段时间后，脚本提示 "正在打歌中..." *、* 游戏仍然停留在结算界面

## 环境
分辨率：2400 x 1080
Android 版本：13
系统版本：MIUI 14
Phigros 版本：3.1.3

**Comment by Xizo-114514** [comment]
1.可能是延时不够，没有等到按钮加载出。尝试将main_xizo.py中第294和296行的延时数值适当改大一点，再尝试是否可用。
2.可能是没有点到正确的位置，尝试将main_xizo.py中第244行的坐标修改一下，定位到左上角的重试按钮。可能较宽的屏幕比例按钮位置有一定偏移。
以上两点是我目前想到的修改方式，如果还不行再反馈

**Comment by UnspokenSpell** [comment]
将main_xizo.py中第244行的坐标为(70,70)可以解决问题。😃 对于1080p，(30,30)可能太偏向左上角了。🧐

**Comment by UnspokenSpell** [comment]
## 🔰 提高兼容性的建议

建议在第175行下面加上
`return_btn_x = return_btn_y = int(device_height/12)`

然后把原第244行改成
`self.controller.tap(return_btn_x, return_btn_y)`


我测试过了，可以适应更多的比例和分辨率的屏幕。😜
